services:
  - type: web
    name: blog-list-backend
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        fromDatabase:
          name: phonebook-mongodb
          property: connectionString
    healthCheckPath: /api/blogs 